spring:
  redis:
    host: 127.0.0.1
    password: tree
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #org.postgresql.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/user?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        #JPA @Column 设置字段名无效
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #使用innodb
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        #show_sql: true #//控制台是否打印
        #format_sql: true #//格式化sql语句
        #use_sql_comments: true #//指出是什么操作生成了该语句
    http:
      encoding:
        charset: UTF-8
        enabled: true
#自定义配置
ncov:
  base: /Users/tree/IdeaProject_Local/ncov-demo/file #base目录
  ds:
    name: pg #使用数据库类型
  cbndata:
    from: remote
    truncate: true #是否自动清除
    remote:
      filename: data.json
      url: https://assets.cbndata.org/2019-nCoV/data.json
    local:
      filename: ncov_addr_detail.csv
      url: ${ncov.base}/${ncov.cbndata.local.filename}
  githubdata:
    from: local
    truncate: true #是否自动清除
    remote:
      overall:
        json:
          url: https://lab.isaaclin.cn/nCoV/api/overall
      area:
        json:
          url: https://lab.isaaclin.cn//nCoV/api/area?latest=1
          filename: DXYArea.json
        zip:
          url: https://github.com/BlankerL/DXY-COVID-19-Data/archive/master.zip
          filename: master.zip
    local:
      json:
        filename: DXYArea.json
        url: ${ncov.base}/${ncov.githubdata.local.json.filename}
      csv:
        filename: DXYArea.csv
        url: ${ncov.base}/${ncov.githubdata.local.csv.filename}





